version: '3.1'

services:
  app:
    container_name: code-house-task
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=phoneBook