spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phoneBook
    username: test
    password: test

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    mapper:
      accept-case-insensitive-enums: true

logging:
  level:
    tracer: TRACE
    org.zalando.logbook: TRACE
    org.hibernate.SQL: DEBUG
    com.netflix.eureka: 'OFF'
    org.elasticsearch.client.RestClient: ERROR
